name: Deploy to NuxtHub

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1.1.4
